kind: pipeline
type: docker
name: backend

trigger:
  branch:
    - feat.*
    - fix.*
    - master
    - main
  event:
    include:
      - push
    exclude:
      - tag
      - pull_request

services:
  - name: postgres-service
    image: postgres:9.6.17-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust

steps:
  - name: check-go-mod
    image: golang:alpine
    commands:
      - apk add git
      - go mod tidy
      - go mod vendor
      - CHANGES=0; [ -z "$(git status --porcelain)" ] || CHANGES=1
      - exit "$CHANGES"
  - name: lint
    image: golangci/golangci-lint:v1.33-alpine
    commands:
      - apk --no-cache add git
      - golangci-lint run -v
  - name: build
    image: golang:alpine
    commands:
      - go build -o ./journal-api ./cmd/api
      - go build -o ./journal-migrate ./cmd/migrate
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    depends_on:
      - check-go-mod
      - lint
  - name: unit-tests
    image: golang:alpine
    commands:
      - go test --tags=unit -mod=vendor -covermode=atomic -coverprofile=profile.cov -v ./...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    depends_on:
      - build
  - name: integration-tests
    image: golang:alpine
    commands:
      - sleep 5
      - ./journal-migrate up
      - go test --tags=integration -mod=vendor -covermode=atomic -coverprofile=profile.cov -v ./...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
      PGHOST: postgres-service
      PGPORT: 5432
      PGDATABASE: testdb
      PGUSER: testuser
      PGPASSWORD: password
      PGSSLMODE: disable
      PG_CONN_STRING: postgres://testuser:password@postgres-service:5432/testdb?sslmode=disable
    depends_on:
      - build
  - name: e2e-tests
    image: golang:alpine
    commands:
      - ./journal-api &
      - sleep 1
      - go test --tags=e2e -mod=vendor -covermode=atomic -coverprofile=profile.cov -v ./cmd/...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
      PGHOST: postgres-service
      PGPORT: 5432
      PGDATABASE: testdb
      PGUSER: testuser
      PGPASSWORD: password
      PGSSLMODE: disable
      JWT_ISSUER: e2e-tester
      JWT_PRIVATE_KEY: private_key
    depends_on:
      - unit-tests
      - integration-tests

---

kind: pipeline
type: docker
name: release

trigger:
  ref:
    - refs/heads/main
    - refs/tags/*

steps:
  - name: docker-build-api
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_api_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      dockerfile: deployments/container/api.Dockerfile
  - name: docker-build-migrate
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_migrate_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      dockerfile: deployments/container/migrate.Dockerfile
  - name: docker-build-ui
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_ui_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      dockerfile: deployments/container/ui.Dockerfile