// source: domain.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.github.com.EmptyShadow.eltech.journal.api.FullName', null, global);
goog.exportSymbol('proto.github.com.EmptyShadow.eltech.journal.api.User', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.EmptyShadow.eltech.journal.api.FullName, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.EmptyShadow.eltech.journal.api.FullName.displayName = 'proto.github.com.EmptyShadow.eltech.journal.api.FullName';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.EmptyShadow.eltech.journal.api.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.EmptyShadow.eltech.journal.api.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.EmptyShadow.eltech.journal.api.User.displayName = 'proto.github.com.EmptyShadow.eltech.journal.api.User';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.EmptyShadow.eltech.journal.api.FullName.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.EmptyShadow.eltech.journal.api.FullName} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.toObject = function(includeInstance, msg) {
  var f, obj = {
    firstname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    middlename: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastname: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.FullName}
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.EmptyShadow.eltech.journal.api.FullName;
  return proto.github.com.EmptyShadow.eltech.journal.api.FullName.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.EmptyShadow.eltech.journal.api.FullName} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.FullName}
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMiddlename(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.EmptyShadow.eltech.journal.api.FullName.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.EmptyShadow.eltech.journal.api.FullName} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFirstname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMiddlename();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string FirstName = 1;
 * @return {string}
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.prototype.getFirstname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.FullName} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.prototype.setFirstname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string MiddleName = 2;
 * @return {string}
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.prototype.getMiddlename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.FullName} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.prototype.setMiddlename = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string LastName = 3;
 * @return {string}
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.prototype.getLastname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.FullName} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.FullName.prototype.setLastname = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.EmptyShadow.eltech.journal.api.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.EmptyShadow.eltech.journal.api.User} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pwd: msg.getPwd_asB64(),
    fullname: (f = msg.getFullname()) && proto.github.com.EmptyShadow.eltech.journal.api.FullName.toObject(includeInstance, f),
    createdat: (f = msg.getCreatedat()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedat: (f = msg.getUpdatedat()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedat: (f = msg.getDeletedat()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.EmptyShadow.eltech.journal.api.User;
  return proto.github.com.EmptyShadow.eltech.journal.api.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.EmptyShadow.eltech.journal.api.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPwd(value);
      break;
    case 4:
      var value = new proto.github.com.EmptyShadow.eltech.journal.api.FullName;
      reader.readMessage(value,proto.github.com.EmptyShadow.eltech.journal.api.FullName.deserializeBinaryFromReader);
      msg.setFullname(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedat(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedat(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.EmptyShadow.eltech.journal.api.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.EmptyShadow.eltech.journal.api.User} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPwd_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getFullname();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.github.com.EmptyShadow.eltech.journal.api.FullName.serializeBinaryToWriter
    );
  }
  f = message.getCreatedat();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedat();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedat();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ID = 1;
 * @return {string}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Email = 2;
 * @return {string}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes Pwd = 3;
 * @return {string}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getPwd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes Pwd = 3;
 * This is a type-conversion wrapper around `getPwd()`
 * @return {string}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getPwd_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPwd()));
};


/**
 * optional bytes Pwd = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPwd()`
 * @return {!Uint8Array}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getPwd_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPwd()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.setPwd = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional FullName FullName = 4;
 * @return {?proto.github.com.EmptyShadow.eltech.journal.api.FullName}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getFullname = function() {
  return /** @type{?proto.github.com.EmptyShadow.eltech.journal.api.FullName} */ (
    jspb.Message.getWrapperField(this, proto.github.com.EmptyShadow.eltech.journal.api.FullName, 4));
};


/**
 * @param {?proto.github.com.EmptyShadow.eltech.journal.api.FullName|undefined} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
*/
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.setFullname = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.clearFullname = function() {
  return this.setFullname(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.hasFullname = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp CreatedAt = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getCreatedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
*/
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.setCreatedat = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.clearCreatedat = function() {
  return this.setCreatedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.hasCreatedat = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp UpdatedAt = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getUpdatedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
*/
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.setUpdatedat = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.clearUpdatedat = function() {
  return this.setUpdatedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.hasUpdatedat = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp DeletedAt = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.getDeletedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
*/
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.setDeletedat = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.EmptyShadow.eltech.journal.api.User} returns this
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.clearDeletedat = function() {
  return this.setDeletedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.EmptyShadow.eltech.journal.api.User.prototype.hasDeletedat = function() {
  return jspb.Message.getField(this, 7) != null;
};


goog.object.extend(exports, proto.github.com.EmptyShadow.eltech.journal.api);
