version: '3.4'

services:
  journal:
    build:
      context: ../../
      dockerfile: ../container/Dockerfile-journal
    restart: on-failure
    env_file:
      - ./configs/journal.env
    ports:
      - "80"   # UI
      - "7010" # HTTP health
      - "7020" # HTTP profiling
      - "9000" # gRPC API
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.17-alpine
    restart: "no"
    env_file:
      - ./configs/postgres.env
    volumes:
      - postgres-data:/data/postgres
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:4.26
    user: "$UID:$GID"
    env_file:
      - ./configs/pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5480:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: