version: '3.4'

services:
  ui:
    build:
      context: ../../
      dockerfile: deployments/container/ui.Dockerfile
    restart: on-failure
    ports:
      - "80"
    depends_on:
      - api
  api:
    build:
      context: ../../
      dockerfile: deployments/container/api.Dockerfile
    restart: on-failure
    env_file:
      - ../../configs/api.env
    ports:
      - "7010:7010"
      - "9000:9000"
      - "8000:8000"
    depends_on:
      - postgres
      - migrate
  migrate:
    build:
      context: ../../
      dockerfile: deployments/container/migrate.Dockerfile
    restart: on-failure
    env_file:
      - ../../configs/migrate.env
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.17-alpine
    restart: "no"
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/data/postgres
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres-data: