version: '3.4'

services:
  journal:
    build:
      context: ../../
      dockerfile: deployments/container/journal.Dockerfile
    restart: on-failure
    env_file:
      - ../../configs/journal.env
    ports:
      - "7010"
      - "9000"
    depends_on:
      - postgres
      - migrate
  migrate:
    build:
      context: ../../
      dockerfile: deployments/container/migrate.Dockerfile
    restart: on-failure
    env_file:
      - ../../configs/migrate.env
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.17-alpine
    restart: "no"
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/data/postgres
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres-data: